name: "000"
id: "000"
gpus: [0,1,3, 4, 5, 6, 7, 8, 9, 10, 11]
port: 8001

pranc:
  seed: 0 
  num_alpha: 100

experiment:
  mode: 'train'   #[train, test]
  method: 'normal'   #[normal, pranc, pranc_bin]
  loss: "focal"   #[cross-entropy, mse]
  lr: 0.001
  optimizer: 'sgd'  #[sgd, adam]
  # momentum: 0.9 #momentum for sgd
  # weight_decay: 0.0001 #weight decay for sgd
  scheduler: 'step' #[none, step, exponential]
  gamma: 0.5 #gamma for exponential and step scheduler 
  step: 5  #step for step scheduler
  epoch: 100

  batch_size: 24   #optional for testing
  # resume: 'R18_IMAGENET/pranc'  #for resuming pranc training. 
  # resume: '<TASK_ID>/best_model.pt'  #for resuming normal training. 
  # load_model: '<TASK_ID>/pranc' #for pranc testing
  # load_model: '<TASK_ID>/best_model.pt' #for normal testing 
  task: 'potsdam' #[mnist, cifar10, cifar100, tiny, imagenet]
  model_arch: 'segmentationresnet50' #'segmentationresnet' #'deeplabv3'  #[lenet, resnet18, resnet20, resnet56, alexnet, convnet]

dataset:
  image_width: 300 # set 28 for mnist, 32 for cifar, 64 tiny, 256 for imagenet
  dataset_path: './datasets/iSAID'    #path to the dataset

monitor:  #optional for testing
  log_rate: 50
  save_model: 'best_modelnormal.pt'    #if touch, modify resume and load_model
  save_path: 'normal'      #if touch, modify resume and load_model